version: "3"

services:
  reverse-proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
        - '80:80'
        - '443:443'
        - '8080:8080'
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  web:
    build: ./
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/devblog?schema=public
    volumes: 
      - ./:/usr/app/web
      - /usr/app/web/node_modules
    ports: 
      - 3000:3000
    container_name: devblog_web
    depends_on:
      - db
    labels:
      - 'traefik.http.routers.web.rule=Host(`devblog.localhost`)'

  db:
    image: postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
    container_name: devblog_db

volumes:
  database-data:
    name: devblog